### ISSUE TITLE
Impossible to use %10@SwitchBuffer@foo.c%X pattern in tabline

### ISSUE THREAD

**Issue by mildred** [itchyny/lightline.vim#240]
In `:help 'statusline'`, there is an example that uses a `%N@Function@Label%X` syntax to provide clickable labels in the tabline. This pattern doesn't seem to work with lightline.

For example I have a function called `bufmru#lightline#buffers` that returns the following string: `%1@bufmru#lightline#bufgo@1: a%X %2@bufmru#lightline#bufgo@2: b%X`

I also have a function `bufmru#lightline#bufgo` that perform some action depending on its arguments.

If the first function (`bufmru#lightline#buffers`) is registered in `lightline.component_function`, and I use the component in the tabline, I get the raw string with the `%` sequence uninterpreted. If instead I register the component in `lightline.component_expand`, I see nothing on the tabline at all.

I find there is missing documentation on how to use these escape sequences. I think that `lightline.component_type` might help me but there is almost no documentation on it. Setting the component type to `raw` doesn't help either. Reading the code it seems that lightline is already setting clickable areas in the tabline and it might conflict.

How to make a component with multiple labels that are clickable to a function of my own?

Thank you.

**Comment by itchyny** [comment]
I'm afraid I cannot find that example in the statusline help. I tried setting `let &tabline = '%1@bufmru#lightline#bufgo@1: a%X %2@bufmru#lightline#bufgo@2: b%X'` with bufmru installed but it doesn't seem to work well. Can you provide a working example?
<img width="449" alt="screen shot 2017-08-09 at 11 22 50" src="https://user-images.githubusercontent.com/375258/29102587-2b08dc76-7cf5-11e7-8588-b5d3bde10323.png">

**Comment by mildred** [comment]
I use the help of neovim v0.2.0:

        item  meaning                                                                                                                                   
        ...
        T N   For 'tabline': start of tab page N label.  Use %T or %X to end                                                                            
              the label.  Clicking this label with left mouse button switches                                                                           
              to the specified tab page.                                                                                                                
        X N   For 'tabline': start of close tab N label.  Use %X or %T to end                                                                           
              the label, e.g.: %3Xclose%X.  Use %999X for a "close current                                                                              
              tab" label.    Clicking this label with left mouse button closes                                                                          
              specified tab page.                                                                                                                       
        @ N   For 'tabline': start of execute function label. Use %X or %T to                                                                           
              end the label, e.g.: %10@SwitchBuffer@foo.c%X.  Clicking this                                                                             
              label runs specified function: in the example when clicking once                                                                          
              using left mouse button on "foo.c" "SwitchBuffer(10, 1, 'l',                                                                              
              '    ')" expression will be run.  Function receives the                                                                                   
              following arguments in order:                                                                                                             
              1. minwid field value or zero if no N was specified                                                                                       
              2. number of mouse clicks to detect multiple clicks                                                                                       
              3. mouse button used: "l", "r" or "m" for left, right or middle                                                                           
                 button respectively; one should not rely on third argument                                                                             
                 being only "l", "r" or "m": any other non-empty string value                                                                           
                 that contains only ASCII lower case letters may be expected                                                                            
                 for other mouse buttons                                                                                                                
              4. modifiers pressed: string which contains "s" if shift                                                                                  
                 modifier was pressed, "c" for control, "a" for alt and "m"                                                                             
                 for meta; currently if modifier is not pressed string                                                                                  
                 contains space instead, but one should not rely on presence                                                                            
                 of spaces or specific order of modifiers: use stridx() to                                                                              
                 test whether some modifier is present; string is guaranteed                                                                            
                 to contain only ASCII letters and spaces, one letter per                                                                               
                 modifier; "?" modifier may also be present, but its presence                                                                           
                 is a bug that denotes that new mouse button recognition was                                                                            
                 added without modifying code that reacts on mouse clicks on                                                                            
                 this label.                                                                                                                            
              Note: to test whether your version of Neovim contains this                                                                                
                    feature use has('tablineat').                                                                                                       

But for some reason, I can't make it work properly, and I wrongly assumed it was because of lightline, sorry. My example is:

```
function Func(minwid, clicks, btn, modifiers) abort
  echo 'Func()'
  echo 'num: ' . a:minwid
  echo 'clicks: ' . a:clicks
  echo 'btn: ' . a:btn
  echo 'modifiers: ' . a:modifiers
  let g:res='Func('.a:minwid.', '.a:clicks.', '.a:btn.', '.a:modifiers.')'
  echo g:res
endfunction

func MyOwnTabLine()
  return 'tabline: %10@Func@Label%X (end)'
endfunction

let g:res='none'
set showtabline=2
set tabline=%!MyOwnTabLine()
```

(run using nvim -u exmple.vim foo`)

**Comment by mildred** [comment]
I reported the issue with neovim, and it seems the issue was that mouse support was not enabled https://github.com/neovim/neovim/issues/7139

The above example works when `set mouse=a` is added. i'll try to reproduce it with lightline in a contained environment and report back here if it doesn't work.

**Comment by mildred** [comment]
I have an isolated test case to run with neovim `nvim -u tabline.vim foo` with tabline.vim containing:

```
call plug#begin('~/.vim/bundle')
Plug 'itchyny/lightline.vim'
call plug#end()

function Func(minwid, clicks, btn, modifiers) abort
  echo 'Func()'
  echo 'num: ' . a:minwid
  echo 'clicks: ' . a:clicks
  echo 'btn: ' . a:btn
  echo 'modifiers: ' . a:modifiers
  let g:res='Func('.a:minwid.', '.a:clicks.', '.a:btn.', '.a:modifiers.')'
  echo g:res
endfunction

func MyTabLine()
  return 'tabline: %10@Func@Label%X (end)'
endfunction

func TestTabline()
  return 'tabline: %10@Func@Label%X (end)'
endfunction

func TestRawTabline()
  return 'tabline raw: %10@Func@Label%X (end)'
endfunction

let g:res='none'
set showtabline=2
set mouse=a
set tabline=%!MyTabLine()

let g:lightline = {
      \ 'tabline': {
      \   'left':  [[ 'testtabline' ]],
      \   'right': [[ 'testrawtabline' ]],
      \ },
      \ 'component_function': {
      \   'testtabline': 'TestTabline',
      \ },
      \ 'component_expand': {
      \   'testrawtabline': 'TestRawTabline',
      \ },
      \ 'component_type': {
      \   'testrawtabline': 'raw',
      \ },
      \ }
```

I use the Plug plugin manager, but it should work with other plugin managers too. Comment out the plugin line and you have the neovim feature test case. With the lightline plugin enabled, I expected to be able to see the same thing.

I tested with two components : a testtabline on the left of the tabline that is using component_function, and a testrawtabline on the right using component_expand with a type set to raw.

**Comment by mildred** [comment]
Expected behavior:

- one of the components, left or right, should display `tabline: Label (end)` or  `tabline (raw): Label (end)`
- clicking on that component should run Func and echo something

Actual behavior:

- The left component contains the string with escape sequences shown `tabline: %10@Func@Label%X (end)`
- The right component shows nothing
- clicking doesn't work

**Comment by itchyny** [comment]
You're definitely correct. I found that raw type is not supported for expansion components. Now I think you can register `bufmru#lightline#buffers` to `component_expand` plus `component_type` to `raw` and it should work.

**Comment by mildred** [comment]
Many thanks ! Especially for the really quick response and fix. :)

**Comment by mildred** [comment]
@itchyny In the above case it seems that setting the component type to raw excludes it from the colorscheme. Do you have an idea on how to implement the coloring in that case? Thank you.

**Comment by itchyny** [comment]
Sorry, I think I have fixed it.

**Comment by mildred** [comment]
Thank you again, I admit reading your commits and not understanding it all. I still don't understand how component_types are working. Can you give me more details on it?

Basically, I want to implement a tabline for buffers. I need to highlight a given buffer (because it is the active one). Reading the documentation in this context it seems that the component_type is exactly what I need. I set my component type to `tabsel` and return an array of three values. The first and last values are highlightes according to the tabline default color while the middle element is going to be highlighted using the `tabsel` color.

However, because I am using the raw type, I cannot set the type to tabsel to get the correct color.

How do you think this case should be handled?

I am thinking that I can insert the `%#highlight#` escape sequences to the value I am returning but I have no idea of the element placement to get the correct highlight group. Perhaps this could be advertised to the component somehow.

It is also possible to let the component return an array of dictionaries containing the value to insert and the color name to use. Something like `return ['non highlighted', {'type': 'tabsel', 'content': 'highlighted tab'}, 'non highlighted']`. In that case, n othing is preventing the function from returning more than three items too.

It is also possible to treat whenever a component is raw or not outside the component_types dictionnary. Instead a component could be declared raw using `'component_raw': {'mycomponent': true}` so it is possible to specify a type at the same time `'component_type': { 'mycomponent': 'tabsel' }`

Or perhaps I just don't understand how it works already.

**Comment by itchyny** [comment]
Yeah, I think of this mistake of the configuration design when people ask me how to use raw type component. It was a critical mistake to have _raw component_ to be configured via `component_type`. Your suggestion is reasonable and I'll implemet `component_raw`. Please be patient for a few days, for rethinking the design, implementation and testing.

**Comment by mildred** [comment]
thank you a lot :)
